# Домашнее задание #1

In [141]:
import numpy as np

Задача №1

Считайте (через input) 2 числа:
n - размер Numpy вектора;
x - координата элемента вектора, который должен быть равен 1. Остальные должны быть равны 0.
Создайте вектор размера n, в котором все элементы равны 0, кроме элемента с номером x - он равен 1.

In [144]:
 print("Введите размер матрицы через пробел")
n, x = map(int, input().split())

Введите размер матрицы через пробел
5 2


In [146]:
vec = np.zeros(n)
vec[x] = 1
print(vec)

[0. 0. 1. 0. 0.]


Задача №2

Считайте 3 числа: n, m, s. Создайте Numpy вектор, состоящий из чисел от n до m с шагом s.

In [ ]:
print("Введите три числа через пробел")

In [77]:
n, m, s = map(int, input().split())
vec1=np.arange(n, m, s)
print(vec1)

Введите три числа через пробел
1 9 1
[1 2 3 4 5 6 7 8]


Задача №3

Создайте матрицу 3х3 со значениями от 0 до 8. Значения нужно сгенерировать.

In [78]:
vec3 = np.random.randint(0, 8, size=(3,3))
print(vec3)

[[3 5 3]
 [3 2 4]
 [7 4 2]]


Задача №4

1. Создайте матрицу 4х4 со случайными значениями.
2. Найдите максимальное значение первой строки, минимальное - второй, среднее - третьей, сумму - четвертой.

In [101]:
vec3 = np.random.rand(4,4)
print(vec3)
print(f'max {np.max(vec3[0, :])}')
print(f'min {np.min(vec3[1, :])}')
print(f'mean {np.mean(vec3[2, :])}')
print(f'sum {np.sum(vec3[3, :])}')

[[0.74734141 0.70613888 0.44923095 0.57520703]
 [0.45550883 0.19263227 0.26366099 0.73155776]
 [0.24073722 0.8807001  0.40893628 0.72837094]
 [0.43630806 0.44637108 0.32092276 0.91289293]]
max 0.7473414057937595
min 0.19263227337981026
mean 0.5646861376083985
sum 2.1164948377390536


Задача №5

Создайте диагональную матрицу 5х5, все ненулевые элементы равны 5.

In [113]:
vec4=np.eye(5)
print(vec4*5)

[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]


Задача №6

Создайте Numpy массив случайных чисел размерности 6х6х6 и найдите максимальное значение среди всех элементов.

In [149]:
vec5=np.random.rand(6,6,6)
print(np.max(vec5))

0.991790357785763


Задача №7

Напишите функцию, которая принимает на вход 2 Numpy матрицы, проверяет, можно ли их перемножить, и если можно - то перемножает и возвращает транспонированную результирующую матрицу.

In [151]:
def matrix_multiplication(A, B):
    if A.shape[1] == B.shape[0]:
        return np.transpose(A @ B)   
    return "Невозможно перемножать"

Задача №8

Дана функция:

Найдите минимум данной функции, завершив вычисления при погрешности
, выбрав в качестве начального приблежения точку (0, 0) и коэффициент шага


In [153]:
def func(x, y):
    return x*x + 2.0 * y*y + np.exp(x + y)

def f_x(func, x, y, eps=0.001):
    return (func(x+eps, y) - func(x, y)) / eps

def f_y(func, x, y, eps=0.001):
    return (func(x, y+eps) - func(x, y)) / eps

In [154]:
EPS = 0.001
INIT = np.array([1.0, -1.75])
LEARN_RATE = 0.05
ITER = 10000

X_prev = INIT
delta = 1
for i in range(ITER):
    if delta > EPS:
        fxx = f_x(func, X_prev[0], X_prev[1], eps=0.001)
        fyy = f_y(func, X_prev[0], X_prev[1], eps=0.001)
        grad = np.array([fxx, fyy])

        X_next = X_prev - LEARN_RATE * grad    

        delta = np.sqrt(np.sum(grad*grad))
        
        X_prev = X_next
        
    else:
        break

In [155]:
print(f"Значение функции {func(X_next[0], X_next[1]).round(4)}")
print(f"x_min {X_next[0].round(4)}")
print(f"y_min {X_next[1].round(4)}")
print(f"Производная в x_min {f_x(func, X_next[0], X_next[1], eps=0.001).round(4)}")
print(f"Производная в y_min {f_y(func, X_next[0], X_next[1], eps=0.001).round(4)}")
print(f"Градиент {np.sqrt((grad**2).sum()).round(9)}")

Значение функции 0.7723
x_min -0.3128
y_min -0.1569
Производная в x_min 0.0008
Производная в y_min -0.0002
Градиент 0.000963264
